### ISSUE TITLE
Improve display of Lato font

### ISSUE THREAD

**Issue by jacobtylerwalls** [azavea/green-equity-demo#43]
## Overview
In Safari, and possibly other browsers, the Lato font doesn't render well. It could be something to do with antialiasing defaults across browsers.

### Demo
![Screenshot 2023-02-28 at 4 47 04 PM](https://user-images.githubusercontent.com/38668450/221993390-9d478b8f-0b9b-4b0a-bab9-0497ff272607.png)

### Additional context
Investigate whether we can provide a font-smoothing css prop to fix this, else find a suitable font.

**Comment by stephwall** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Apps-62c5ba9ee84ced001f5b5d00/issues/azavea/green-equity-demo/43?planning-poker) with Zenhub @jacobtylerwalls @JN-Hernandez @mstone121 @rachelekm @rajadain
