### ISSUE TITLE
Extra Whitespace / Horizontal Scrolling

### ISSUE THREAD

**Issue by rajadain** [azavea/green-equity-demo#46]
## Overview

There is extra whitespace to the right of the page, causing horizontal scrolling where there should be none.

### Steps to Reproduce

- Go to https://azavea.github.io/green-equity-demo/
- Scroll right

### Demo

https://user-images.githubusercontent.com/1430060/222277026-fb2a4497-f61b-49f1-944a-f1c38b0a3999.mp4

**Comment by mstone121** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Apps-62c5ba9ee84ced001f5b5d00/issues/azavea/green-equity-demo/46?planning-poker) with Zenhub @jacobtylerwalls @JN-Hernandez @mstone121 @rachelekm @rajadain
