### ISSUE TITLE
Improve page responsiveness

### ISSUE THREAD

**Issue by mstone121** [azavea/green-equity-demo#51]
## Overview

Some of the site components don't look great on small screen sizes. This card also includes investigating the feasibility of making this site mobile friendly.

<img width="422" alt="Screenshot 2023-03-02 at 1 45 17 PM" src="https://user-images.githubusercontent.com/8356789/222535974-62ca5b61-b489-4c98-87e0-a9f38637808a.png">

**Comment by stephwall** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Apps-62c5ba9ee84ced001f5b5d00/issues/azavea/green-equity-demo/51?planning-poker) with Zenhub @jacobtylerwalls @JN-Hernandez @mstone121 @rachelekm @rajadain

**Comment by stephwall** [comment]
We should consult @svandekerkhof on this one.
