### ISSUE TITLE
Some files are not formatted

### ISSUE THREAD

**Issue by mstone121** [azavea/green-equity-demo#56]
When there isn't a lot of development activity going on, it would be nice to format some of the files that aren't currently formatted. 

The formatting can be performed by running:
```zsh
npx prettier **/*.tsx -w && npx prettier **/*.ts -w
```
in `src/app` if `node_modules` are installed locally. Also, you might need to remove `"parser": "babel"` from `.prettierrc`.

Installing the `Prettier` extension VS code should enable the format-on-save functionality we have in other projects.

**Comment by jacobtylerwalls** [comment]
I'll look into getting my IDE rigged up correctly. Relatedly, why is CI not failing these PRs? MegaLinter should be running prettier. We may need to do something similar to azavea/azavea-project-template@cf74b50ac05f5fe7ef83c39f118d3b0691e079f7.

**Comment by mstone121** [comment]
Looks like it's not linting typescript files. I tried to fix this with https://github.com/azavea/green-equity-demo/commit/c7327e24a35390444744361ffec8c4916189e55d, but it didn't seem to work.

**Comment by jacobtylerwalls** [comment]
I'll take a look if you don't mind. There's a solution described at https://github.com/oxsecurity/megalinter/issues/782.

**Comment by jacobtylerwalls** [comment]
> Installing the Prettier extension VS code should enable the format-on-save functionality we have in other projects.

In my case, I had to both edit the "Editor: Default Formatter" setting and the "Editor: Format on Save" setting.
