### ISSUE TITLE
Add markers to per-capita map legend

### ISSUE THREAD

**Issue by mstone121** [azavea/green-equity-demo#70]
## Overview

<img width="210" alt="Screenshot 2023-03-14 at 11 01 41 AM" src="https://user-images.githubusercontent.com/8356789/225064111-dda12b28-cb62-4dbe-ba34-645453c6a838.png">

**Comment by mstone121** [comment]
@svandekerkhof Does the screenshot above accurately reflect the final design?

**Comment by svandekerkhof** [comment]
as much as I like the little people icons, I think they need more context for people to understand them and there's very little space here. We can discuss more during the check-in today but I'll delete the icons for now from the design in Figma.

**Comment by mstone121** [comment]
At check-in we decided we're going forward with no markers.
