### ISSUE TITLE
Change hover outline color

### ISSUE THREAD

**Issue by mstone121** [azavea/green-equity-demo#73]
The black outline doesn't have great contrast with the state fill color. Update it to match the figma design:

![](https://user-images.githubusercontent.com/101655557/225488836-41da284c-4a37-40d2-9837-bd82826d09f6.png)

**Comment by mstone121** [comment]
@svandekerkhof When you decide on a color, would you mind adding it here?

**Comment by svandekerkhof** [comment]
I asked this question in the UX team slack and got some great options. The color I think works best is a white stroke with a drop shadow so that there will always be enough contrast. The design is in the Figma file, how much info do you want me to paste here next to an screenshot?
<img width="268" alt="hover outline color" src="https://user-images.githubusercontent.com/101655557/225488836-41da284c-4a37-40d2-9837-bd82826d09f6.png">

**Comment by mstone121** [comment]
The screenshot is fine. Whoever takes the card can reference the Figma design. I'll update the description. Thanks!

**Comment by mstone121** [comment]
I noticed that the updated design also makes non-hovered states' borders white. This makes the map look like it has gaps when a state has no funding for a specific category because the color for these states is also white:

<img width="446" alt="Screenshot 2023-03-17 at 2 43 25 PM" src="https://user-images.githubusercontent.com/8356789/226013749-b21de044-dede-4f52-b34b-94f292517917.png">

**Comment by mstone121** [comment]
Discussed in check-in: let's make the fill color grey for states with no spending.

**Comment by travissouthard** [comment]
Gray (this is the native `'gray'` color) is a little rough looking in here. Does it make sense to go pick a color from the palette @svandekerkhof?
![image](https://user-images.githubusercontent.com/64238570/231773281-876e3cd4-2c1c-4090-b43f-37069bd70315.png)

For example: 
![image](https://user-images.githubusercontent.com/64238570/231775470-3b6be3f2-d7d1-4395-a889-68e74e3e7329.png)

**Comment by mstone121** [comment]
Can we try having the no spending states have a fill color of gray rather than a border? That might look better especially where the other states overlap the border.

**Comment by travissouthard** [comment]
You did say _**fill**_ color! Yeah that looks much better!

![image](https://user-images.githubusercontent.com/64238570/231786568-eb4d9dcb-aecf-4f4f-a1b4-764ce441b6df.png)
