### ISSUE TITLE
Investigate Leaflet attribution

### ISSUE THREAD

**Issue by mstone121** [azavea/green-equity-demo#74]
There isn't really a not awkward place to have this on our maps (though perhaps this might not be the case if we "merge" the maps), so investigate if we need this attribution (or even if we're just terrible people for not including it) and remove it if possible. 

Another options is to move the attribution to the Methodology section in the footer.

**Comment by rajadain** [comment]
https://gis.stackexchange.com/questions/192088/how-to-remove-attribution-in-leaflet
