### ISSUE TITLE
Make Animated Map use per capita data

### ISSUE THREAD

**Issue by rachelekm** [azavea/green-equity-demo#80]
## Overview

An expanded issue based off of discussion on #63, we should update the animated map to use per capita spending data. That includes:

- Update the spending over time data used by the animated map so the values illustrate per capita spending and conditional layer style colors match per capita bucket ranges.
- Update the map legend to represent the per capita ranges

**Comment by stephwall** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Apps-62c5ba9ee84ced001f5b5d00/issues/azavea/green-equity-demo/80?planning-poker) with Zenhub @jacobtylerwalls @JN-Hernandez @mstone121 @rachelekm @rajadain
